// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClusterBounds2 = { min_x: number, max_x: number, min_z: number, max_z: number, };
