// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClusterBounds2 } from "./ClusterBounds2";

export type ClusterRectangle = { id: string, bounds: ClusterBounds2, vertex_count: number, };
