// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClusterBounds2 } from "./ClusterBounds2";
import type { Vertex3 } from "./Vertex3";

export type Cluster2 = { id: string, bounds: ClusterBounds2, vertices: Array<Vertex3>, };
