// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cluster2 } from "./Cluster2";
import type { ClusterRectangle } from "./ClusterRectangle";

export type ClusteringResult2 = { clusters: Array<Cluster2>, cluster_rectangles: Array<ClusterRectangle>, };
