// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Vertex3 } from "./Vertex3";

export type ClusterBounds2 = { bottom_left: Vertex3, bottom_right: Vertex3, top_right: Vertex3, top_left: Vertex3, };
