// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Vertex3 } from "./Vertex3";

export type SimplificationResult = { simplified_vertices: Array<Vertex3>, };
