// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Vertex3 } from "./Vertex3";

export type Tetrahedron3 = { id: string, a: Vertex3, b: Vertex3, c: Vertex3, d: Vertex3, };
