// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tetrahedron3 } from "./Tetrahedron3";
import type { Vertex3 } from "./Vertex3";

export type TetrahedralizationResult = { tetrahedra: Array<Tetrahedron3>, vertices: Array<Vertex3>, };
