// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Triangle3 } from "./Triangle3";
import type { Vertex3 } from "./Vertex3";

export type TriangulationResult = { triangles: Array<Triangle3>, vertices: Array<Vertex3>, };
