// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Vertex3 } from "./Vertex3";

export type TriangulationRequest = { vertices: Array<Vertex3>, epsilon: number, };
